events {}

http {
    # 1. Define our pool of backend worker servers
    upstream python_backends {
        # Nginx defaults to Round-Robin load balancing (it will alternate 1, 2, 1, 2...)
        server backend1:8000;
        server backend2:8000;
    }

    server {
        # Nginx listens for incoming traffic on port 80
        listen 80;

        location / {
            # Route all traffic hitting the root '/' to our upstream pool
            proxy_pass http://python_backends;
            
            # Security/Tracking: Forward the original client's IP to the backend
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
        }
    }
}
